### ISSUE TITLE
Hydration error when user is logged in

### ISSUE THREAD

**Issue by JonahKK** [gutentag2012/realworld-nextjs-trpc-prisma#2]
Hi!
I wanted to use your app for presenting some testing techniques, but when I downloaded it, I have encountered an issue with hydration error.

**Steps to reproduce**

1. Run app with `pnpm dev`
2. Go to `localhost:3000`
3. Sign in as test user
4. While being on the main page `Global feed` refresh page.
5. Upon refresh hydration error is displayed. This does not happen when user is not logged in.
![Image 13-02-2024 at 18 48](https://github.com/gutentag2012/realworld-nextjs-trpc-prisma/assets/23238398/be5a9721-3bce-4b5d-ac3f-fe4fda7bbbc4)

**Comment by gutentag2012** [comment]
The issue is due to the usage of `window` in a page that is server-side rendered as described here https://nextjs.org/docs/messages/react-hydration-error

The PR replaces the usages of the direct window access by wrapping it in a client-side hook
